StarrySprouts/ViewModels/ShoppingCartViewModel.cs
using StarrySprouts.Models;

namespace StarrySprouts.ViewModels
{
    public class ShoppingCartViewModel
    {
        public ShoppingCartModel ShoppingCart { get; set; }
        public decimal ShoppingCartTotal { get; set; }
    }
}

StarrySprouts/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StarrySprouts.Models;

namespace StarrySprouts.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly ShoppingCartModel _shoppingCart;

        public OrderController(IOrderRepository orderRepository, ShoppingCartModel shoppingCart)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(OrderModel order)
        {
            _shoppingCart.ShoppingCartItems = _shoppingCart.GetAllShoppingCartItems();

            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your cart is empty");
            }

            if (ModelState.IsValid)
            {
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();
                return RedirectToAction("CompletedCheckout");
            }

            return View(order);
        }

        public IActionResult CompletedCheckout()
        {
            ViewBag.CompletedCheckoutMessage = "Thank you for your order. Your stickers are on the way!";
            return View();
        }
    }
}

StarrySprouts/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using StarrySprouts.Models;
using StarrySprouts.ViewModels;

namespace StarrySprouts.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;

        //Injected through constructor
        public ProductController(IProductRepository productRepository, ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }

        public IActionResult List()
        {
            //ViewBag.CurrentCategory = "Bestsellers";
            //return View(_productRepository.GetAllProducts);

            var productListViewModel = new ProductListViewModel();
            productListViewModel.Products = _productRepository.GetAllProducts;
            productListViewModel.CurrentCategory = "Bestsellers";
            return View(productListViewModel);
        }

        public IActionResult Details(int id)
        {
            var product = _productRepository.GetProductById(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }
        
    }
}

StarrySprouts/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using StarrySprouts.Models;
using StarrySprouts.ViewModels;

namespace StarrySprouts.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ShoppingCartModel _shoppingCart;

        public ShoppingCartController(IProductRepository productRepository, ShoppingCartModel shoppingCart)
        {
            _productRepository = productRepository;
            _shoppingCart = shoppingCart;
        }

        public ViewResult Index()
        {
            _shoppingCart.ShoppingCartItems = _shoppingCart.GetAllShoppingCartItems();

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int productId)
        {
            //Finding the product's ID
            var selectedProduct = _productRepository.GetAllProducts.FirstOrDefault(p => p.ProductId == productId);

            //If the product is not null then we can add it to the cart.
            if (selectedProduct != null && selectedProduct.IsInStock == true)
            {
                _shoppingCart.AddToCart(selectedProduct, 1);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int productId)
        {
            //Finding the product's ID
            var selectedProduct = _productRepository.GetAllProducts.FirstOrDefault(p => p.ProductId == productId);

            //If the product is not null and is in stock then we can add it to the cart.
            if (selectedProduct != null && selectedProduct.IsInStock == true)
            {
                _shoppingCart.RemoveFromCart(selectedProduct);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult ClearShoppingCart()
        {
            _shoppingCart.ClearCart();

            return RedirectToAction("Index");
        }

    }
}

StarrySprouts/Views/ShoppingCart/Index.cshtml
@model ShoppingCartViewModel

<h2>Shopping Cart</h2>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            @*&nbsp; is non-breakable space*@
            <th>&nbsp;</th>
            <th>Selected Amount</th>
            <th>Items</th>
            <th class="text-right">Price: </th>
            <th class="text-right">Subtotal: </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ShoppingCart.ShoppingCartItems)
        {
            <tr>
                <td class="text-center"><a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-productId="@item.Product.ProductId">Decrease Amount</a></td>
                <td class="text-center">@item.Amount</td>
                <td class="text-start">@item.Product.Name</td>
                <td class="text-end">@item.Product.Price.ToString("C")</td>
                <td class="text-end">
                    @((item.Amount * item.Product.Price).ToString("C"))
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4" class="text-end"> Total: </td>
            <td class="text-end"> @Model.ShoppingCartTotal.ToString("C") </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" asp-controller="Product" asp-action="List">Continue Shopping</a>
    <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="ClearShoppingCart">Clear Cart</a>
    <a class="btn btn-primary" asp-controller="Order" asp-action="Checkout">Checkout</a>
</div>